# Not all values need to be explicitly set.  

# Should iacbot update your PR Status Check
pr_status_enabled: true

# Maxium allowable findings, above which
# PR status check will fail
pr_status_thresholds:
    critical: 1
    high: 1
    medium: 999
    low: 999

# Force the status check to pass.  Checks will still be run.
# Effectively the same as raising thresholds to high values.
pr_status_force_pass_enabled: false

# Set to true if you want iacbot to add PR comments
pr_comments_enabled: true


# If set to true, a PR comment will be added, even if
# the status check passes.
pr_comments_on_passed_check_enabled: false

suppress:
  - "ckv-aws-24"
  - "tfsec-aws006"
